version: '3.8'

services:

  pgsql:
    image: postgres:latest
    container_name: postgresql-container
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fastapi_db
    ports:
      - "5432:5432"
    networks:
      - app_network      

  main_app:
    depends_on:
      - pgsql
    build: ./App
    container_name: fastapi-main-app-container
    ports:
      - "8000:8000"
    networks:
      - app_network


networks:
  app_network:
    name: app_network